apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventsphere-frontend
spec:
  replicas: 1  # Set the number of replicas
  selector:
    matchLabels:
      app: eventsphere-frontend
  template:
    metadata:
      labels:
        app: eventsphere-frontend
    spec:
      containers:
      - name: frontend
        image: kiran186/eventsphere-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://eventsphere-backend:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: eventsphere-frontend
spec:
  selector:
    app: eventsphere-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
